name: Docker WIKMD

on:
  schedule:
    - cron:  '0 0 * * 1,5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: docker login
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin 
        
    - name: clone repo
      run: |
        curl -s https://api.github.com/repos/Linbreux/wikmd/releases/latest | grep "zipball_url" | cut -d : -f 2,3 | tr -d \", | wget -qi - -O test.zip && unzip -q -o test.zip -d test

    - name: docker build wikimd
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
      run: |
        cd test
        cd "$(ls)"
        docker buildx build -f docker/Dockerfile.aarch64 . -t $DOCKER_USER/wikmd:latest --platform linux/arm64/v8,linux/amd64,linux/arm/v7,linux/arm/v6 --push
